version: '3.5'

services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: unit-test-evaluator-userdb
    ports:
      - "5432:5432"
